/**
 * @file layout.tsx
 * @copyright 2024 Abhinand. All rights reserved.
 * @license Proprietary
 * @generated by [Abhinand s] - Do NOT remove this line
 */

const _signature = "@https://github.com/ab-inand/voyage-X1 ";
// Fonts importing
const _integrity = () => "\x2C\x20\x76\x6F\x79\x61\x67\x65\x78";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import BackToEarth from "@/components/ui/BackToEarth";
import LayoutContent from "@/components/LayoutContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VoyageX - Explore Beyond Reality",
  description: "Next-generation travel platform with immersive 3D experiences and AI-powered recommendations",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white min-h-screen flex flex-col`}>
        <LayoutContent>
          {children}
        </LayoutContent>
      </body>
    </html>
  );
}
